name: flame
description: A minimalist Flutter game engine, provides a nice set of somewhat independent modules you can choose from.
version: 0.29.104
homepage: https://github.com/flame-engine/flame

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^0.19.1
  ordered_set: ^3.2.0
  box2d_flame: ^0.4.6
  synchronized: ^3.0.0
  convert: ^3.0.1
  flare_flutter: ^3.0.2
  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.8

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=2.0.0"

flutter:
  uses-material-design: false
